import type { SeedProduct } from './productsPart1.js';

export const productsPart2: SeedProduct[] = [
  // Home & Living Expansion (category_id: 3)
  {
    id: 54,
    name: 'Nordic Wooden Tripod Floor Lamp',
    slug: 'nordic-wooden-tripod-floor-lamp',
    category_id: 3,
    price: 4899,
    discount_percent: 20,
    stock: 22,
    rating: 4.8,
    review_count: 51,
    featured: 1,
    is_new: 1,
    image_url: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=800&q=80',
    description: 'Minimalist Scandinavian floor lamp with solid rubberwood tripod legs, linen drum shade, and warm brass foot switch.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=800&q=80']),
    specifications: JSON.stringify({ 'Height': '155 cm', 'Base': 'Solid Natural Oak', 'Socket': 'Standard E27 (Warm LED included)' })
  },
  {
    id: 55,
    name: 'Precision Electric Gooseneck Temperature Kettle',
    slug: 'precision-electric-gooseneck-temperature-kettle',
    category_id: 3,
    price: 4499,
    discount_percent: 18,
    stock: 32,
    rating: 4.8,
    review_count: 65,
    featured: 0,
    is_new: 1,
    image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&q=80',
    description: '1.0L matte stainless steel electric pour-over kettle with 1-degree precision digital temperature control, LCD display, and 60-minute keep warm.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&q=80']),
    specifications: JSON.stringify({ 'Capacity': '1.0 Litre', 'Heating': '1200W Rapid Boil', 'Temperature Range': '40°C - 100°C (1° increment)' })
  },
  {
    id: 56,
    name: 'Velvet Geometric Throw Pillow Set',
    slug: 'velvet-geometric-throw-pillow-set',
    category_id: 3,
    price: 1299,
    discount_percent: 15,
    stock: 48,
    rating: 4.7,
    review_count: 42,
    featured: 0,
    is_new: 0,
    image_url: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=800&q=80',
    description: 'Set of two plush Dutch velvet cushion covers with embroidered gold geometric lines and hidden zippers.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=800&q=80']),
    specifications: JSON.stringify({ 'Size': '45cm x 45cm (Pack of 2)', 'Material': 'Heavyweight Dutch Velvet' })
  },
  {
    id: 57,
    name: 'Aegean Luxury 700 GSM Turkish Cotton Bath Towel Set',
    slug: 'aegean-luxury-700-gsm-turkish-cotton-bath-towel-set',
    category_id: 3,
    price: 3299,
    discount_percent: 20,
    stock: 28,
    rating: 4.9,
    review_count: 54,
    featured: 0,
    is_new: 1,
    image_url: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=800&q=80',
    description: 'Ultra-plush 6-piece towel bundle woven from 100% genuine Aegean Turkish cotton with combed long-staple fibers and double-stitched hems.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=800&q=80']),
    specifications: JSON.stringify({ 'Set Includes': '2 Bath Towels + 2 Hand Towels + 2 Washcloths', 'Density': '700 GSM Hotel Quality', 'Cotton': '100% Ring-Spun Aegean Cotton' })
  },
  {
    id: 58,
    name: 'Clear Stackable Shoe Storage Boxes (6-Pack)',
    slug: 'clear-stackable-shoe-storage-boxes-6-pack',
    category_id: 3,
    price: 2499,
    discount_percent: 18,
    stock: 40,
    rating: 4.7,
    review_count: 63,
    featured: 1,
    is_new: 0,
    image_url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=80',
    description: 'Drop-front magnetic display sneaker boxes engineered from ultra-clear rigid acrylic with interlocking modular tabs.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=80']),
    specifications: JSON.stringify({ 'Quantity': '6 Crates per pack', 'Max Shoe Size': 'Fits up to Men US 14 / UK 13' })
  },
  {
    id: 59,
    name: 'Drawer Partition Modular Bamboo Organizers',
    slug: 'drawer-partition-modular-bamboo-organizers',
    category_id: 3,
    price: 1499,
    discount_percent: 10,
    stock: 50,
    rating: 4.6,
    review_count: 38,
    featured: 0,
    is_new: 0,
    image_url: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&q=80',
    description: 'Set of 4 spring-loaded expandable natural bamboo drawer dividers with rubber end pads to protect interior surfaces.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&q=80']),
    specifications: JSON.stringify({ 'Material': '100% Organic Moso Bamboo', 'Length': 'Expands 43cm to 56cm' })
  },
  {
    id: 60,
    name: 'ChefCraft 7-Piece Damascus Steel Knife Set',
    slug: 'chefcraft-7-piece-damascus-steel-knife-set',
    category_id: 3,
    price: 9999,
    discount_percent: 25,
    stock: 15,
    rating: 4.9,
    review_count: 84,
    featured: 1,
    is_new: 1,
    image_url: 'https://images.unsplash.com/photo-1593618998160-e34014e67546?w=800&q=80',
    description: 'Artisanal kitchen knife block set forged from 67 layers of Japanese VG-10 Damascus steel with resin Pakkawood handles.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1593618998160-e34014e67546?w=800&q=80']),
    specifications: JSON.stringify({ 'Blade Core': 'Japanese VG-10 High Carbon Steel', 'Hardness': '60±2 HRC', 'Block': 'Magnetic Acacia Wood' })
  },
  {
    id: 61,
    name: 'Pour-Over Borosilicate Glass Carafe & Dripper',
    slug: 'pour-over-borosilicate-glass-carafe-dripper',
    category_id: 3,
    price: 1899,
    discount_percent: 15,
    stock: 42,
    rating: 4.8,
    review_count: 55,
    featured: 0,
    is_new: 1,
    image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&q=80',
    description: 'Heat-resistant manual coffee brewing jug with reusable fine laser-cut double mesh stainless steel cone filter and wooden collar.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&q=80']),
    specifications: JSON.stringify({ 'Capacity': '800ml (4-6 Cups)', 'Glass': 'Thermal Shock Resistant Borosilicate' })
  },
  {
    id: 62,
    name: 'Cast Iron Pre-Seasoned Dutch Oven (5.5 Qt)',
    slug: 'cast-iron-pre-seasoned-dutch-oven-55-qt',
    category_id: 3,
    price: 4299,
    discount_percent: 20,
    stock: 20,
    rating: 4.9,
    review_count: 67,
    featured: 1,
    is_new: 0,
    image_url: 'https://images.unsplash.com/photo-1584990347449-399655811c79?w=800&q=80',
    description: 'Heavyweight enameled cast iron casserole pot delivering superior heat retention for slow roasts, sourdough bread, and soups.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1584990347449-399655811c79?w=800&q=80']),
    specifications: JSON.stringify({ 'Capacity': '5.2 Litres (5.5 Quart)', 'Oven Safe': 'Up to 260°C / 500°F' })
  },
  {
    id: 63,
    name: 'Ceramic Wabi-Sabi Flower Vase',
    slug: 'ceramic-wabi-sabi-flower-vase',
    category_id: 3,
    price: 1199,
    discount_percent: 12,
    stock: 35,
    rating: 4.7,
    review_count: 29,
    featured: 0,
    is_new: 1,
    image_url: 'https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?w=800&q=80',
    description: 'Handcrafted stoneware ceramic vase featuring a textured unglazed sandstone matte exterior and curved sculptural silhouette.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?w=800&q=80']),
    specifications: JSON.stringify({ 'Height': '22 cm', 'Finish': 'Unglazed Textured Sandstone' })
  },
  {
    id: 64,
    name: 'Handwoven Macrame Boho Wall Hanging',
    slug: 'handwoven-macrame-boho-wall-hanging',
    category_id: 3,
    price: 999,
    discount_percent: 15,
    stock: 45,
    rating: 4.5,
    review_count: 38,
    featured: 0,
    is_new: 0,
    image_url: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=800&q=80',
    description: 'Intricately knotted natural cotton macrame tapestry suspended from a polished natural wooden dowel branch.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=800&q=80']),
    specifications: JSON.stringify({ 'Dimensions': '40cm width x 75cm length', 'Yarn': '100% Natural Unbleached Cotton' })
  },
  {
    id: 65,
    name: '100% Washed French Flax Linen Duvet Set',
    slug: '100-percent-washed-french-flax-linen-duvet-set',
    category_id: 3,
    price: 6999,
    discount_percent: 18,
    stock: 18,
    rating: 4.8,
    review_count: 49,
    featured: 1,
    is_new: 1,
    image_url: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&q=80',
    description: 'Pre-washed pure French flax linen king duvet cover with matching pillow shams that softens deliciously with every wash.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&q=80']),
    specifications: JSON.stringify({ 'Includes': '1 King Duvet Cover + 2 Pillow Shams', 'Fiber': '100% Normandy Flax Linen' })
  },
  {
    id: 66,
    name: 'Cooling Gel Infused Memory Foam Pillow Pair',
    slug: 'cooling-gel-infused-memory-foam-pillow-pair',
    category_id: 3,
    price: 2699,
    discount_percent: 22,
    stock: 30,
    rating: 4.7,
    review_count: 57,
    featured: 0,
    is_new: 0,
    image_url: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=800&q=80',
    description: 'Pair of orthopedic cervical pillows with adjustable shredded memory foam filling and double-sided ice silk cooling covers.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=800&q=80']),
    specifications: JSON.stringify({ 'Quantity': '2 Pillows', 'Cover': 'Ice Silk Q-Max 0.4 Cooling Fabric' })
  },
  {
    id: 67,
    name: 'Cordless Handheld Cyclone Mini Vacuum',
    slug: 'cordless-handheld-cyclone-mini-vacuum',
    category_id: 3,
    price: 2999,
    discount_percent: 20,
    stock: 35,
    rating: 4.6,
    review_count: 68,
    featured: 0,
    is_new: 1,
    image_url: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=800&q=80',
    description: 'Compact 12000Pa suction rechargeable vacuum cleaner with HEPA filtration, crevice tool, and brush nozzle for cars and desk setups.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1558317374-067fb5f30001?w=800&q=80']),
    specifications: JSON.stringify({ 'Suction': '12,000 Pa Brushless Motor', 'Battery': '25 min runtime (Type-C charging)' })
  },

  // Fitness Expansion (category_id: 4)
  {
    id: 68,
    name: 'PulsePro Deep Tissue Percussion Massage Gun',
    slug: 'pulsepro-deep-tissue-percussion-massage-gun',
    category_id: 4,
    price: 4999,
    discount_percent: 20,
    stock: 28,
    rating: 4.9,
    review_count: 96,
    featured: 1,
    is_new: 1,
    image_url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80',
    description: 'High-torque brushless motor muscle therapy massage gun delivering 3200 RPM, 6 interchangeable silicone heads, and 30 speed levels.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80']),
    specifications: JSON.stringify({ 'Speed': '30 Adjustable Speed Levels (1200-3200 RPM)', 'Heads': '6 Interchangeable Attachments Included', 'Battery': '2600mAh (6 Hours Runtime)' })
  },
  {
    id: 69,
    name: 'CoreFlex Anti-Burst Exercise & Stability Ball (65cm)',
    slug: 'coreflex-anti-burst-exercise-stability-ball-65cm',
    category_id: 4,
    price: 1399,
    discount_percent: 20,
    stock: 45,
    rating: 4.8,
    review_count: 64,
    featured: 0,
    is_new: 1,
    image_url: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&q=80',
    description: 'Professional grade anti-burst Swiss stability ball rated up to 2000 lbs, featuring matte anti-slip matte ridges, quick inflation foot pump, and workout guide.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&q=80']),
    specifications: JSON.stringify({ 'Diameter': '65cm (Ideal for height 5\'4" to 5\'10")', 'Rating': 'Anti-Burst up to 2,000 lbs', 'Accessories': 'Rapid Foot Pump + Spare Plugs Included' })
  },
  {
    id: 70,
    name: 'EcoPure Natural Tree Rubber Yoga Mat (6mm)',
    slug: 'ecopure-natural-tree-rubber-yoga-mat-6mm',
    category_id: 4,
    price: 2799,
    discount_percent: 18,
    stock: 38,
    rating: 4.8,
    review_count: 83,
    featured: 1,
    is_new: 1,
    image_url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80',
    description: 'Biodegradable natural tree rubber exercise mat with laser-etched body alignment lines and supreme dry/wet grip surface.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80']),
    specifications: JSON.stringify({ 'Thickness': '6mm High Cushion', 'Material': 'Natural Tree Rubber + PU', 'Size': '183cm x 68cm' })
  },
  {
    id: 71,
    name: 'IronGrip Multi-Grip Heavy Duty Doorway Pull-Up Bar',
    slug: 'irongrip-multi-grip-heavy-duty-doorway-pull-up-bar',
    category_id: 4,
    price: 2499,
    discount_percent: 22,
    stock: 35,
    rating: 4.9,
    review_count: 77,
    featured: 1,
    is_new: 1,
    image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&q=80',
    description: 'No-screws doorway chin-up and pull-up bar with 6 ergonomic foam grip positions, heavy-gauge steel construction, and door frame protection pads.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&q=80']),
    specifications: JSON.stringify({ 'Doorway Fit': 'Width 24" - 36", Trim up to 3.5"', 'Max Weight': '150 kg (330 lbs)', 'Grip Options': 'Wide, Narrow, Hammer, Neutral' })
  },
  {
    id: 72,
    name: 'PowerPro Heavy Duty Loop Resistance Bands',
    slug: 'powerpro-heavy-duty-loop-resistance-bands',
    category_id: 4,
    price: 1499,
    discount_percent: 30,
    stock: 55,
    rating: 4.8,
    review_count: 110,
    featured: 0,
    is_new: 1,
    image_url: 'https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=800&q=80',
    description: 'Set of 5 color-coded pull-up assist bands made of 100% Malaysian latex for powerlifting, stretching, and mobility drills.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=800&q=80']),
    specifications: JSON.stringify({ 'Tension': '15 lbs to 125 lbs total range', 'Material': 'Continuous Layered Latex' })
  },
  {
    id: 73,
    name: 'UltraWide Core Ab Roller Wheel with Knee Pad',
    slug: 'ultrawide-core-ab-roller-wheel-with-knee-pad',
    category_id: 4,
    price: 1199,
    discount_percent: 25,
    stock: 48,
    rating: 4.7,
    review_count: 78,
    featured: 0,
    is_new: 0,
    image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&q=80',
    description: 'Extra-wide curved kinetic engine ab workout roller with non-skid rubber tread, ergonomic angled hand grips, and high-density foam knee protector.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&q=80']),
    specifications: JSON.stringify({ 'Wheel Width': '3.7 inch Ultra-Wide Curved', 'Internal Spring': 'Carbon Steel Spring Assistance', 'Max Capacity': '200 kg' })
  },
  {
    id: 74,
    name: 'Cast Iron Competition Kettlebell (16kg)',
    slug: 'cast-iron-competition-kettlebell-16kg',
    category_id: 4,
    price: 2999,
    discount_percent: 15,
    stock: 20,
    rating: 4.9,
    review_count: 54,
    featured: 1,
    is_new: 0,
    image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&q=80',
    description: 'Single-piece cast iron competition kettlebell with uniform dimensions, powder coat grip finish, and wide flat machined base.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&q=80']),
    specifications: JSON.stringify({ 'Weight': '16kg (35.2 lbs)', 'Casting': 'Gravity Cast Gravity Molded Iron' })
  },
  {
    id: 75,
    name: 'ProGrip Ventilated Leather Weightlifting Gloves',
    slug: 'progrip-ventilated-leather-weightlifting-gloves',
    category_id: 4,
    price: 999,
    discount_percent: 20,
    stock: 52,
    rating: 4.8,
    review_count: 81,
    featured: 0,
    is_new: 1,
    image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&q=80',
    description: 'Microfiber & genuine leather gym gloves with silicone honeycomb palm padding, integrated wrist wrap strap, and breathable open-back mesh.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&q=80']),
    specifications: JSON.stringify({ 'Palm': 'Silicone Hex-Pattern + Cowhide Padding', 'Wrist Support': 'Adjustable Hook-and-Loop Wrap', 'Back': 'Four-Way Stretch Mesh' })
  },
  {
    id: 76,
    name: 'SpeedRope Pro Ball-Bearing Jump Rope',
    slug: 'speedrope-pro-ball-bearing-jump-rope',
    category_id: 4,
    price: 799,
    discount_percent: 25,
    stock: 75,
    rating: 4.7,
    review_count: 124,
    featured: 0,
    is_new: 0,
    image_url: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&q=80',
    description: 'High-speed 360-degree dual ball bearing skipping rope with 2.5mm coated steel wire and knurled aluminum non-slip handles.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&q=80']),
    specifications: JSON.stringify({ 'Cable': '3m Adjustable Coated Steel Wire', 'Bearings': 'High Precision 360° Ball Bearings' })
  },
  {
    id: 77,
    name: 'HydraFlow 1.5L Insulated Gym Bottle',
    slug: 'hydraflow-15l-insulated-gym-bottle',
    category_id: 4,
    price: 1599,
    discount_percent: 15,
    stock: 50,
    rating: 4.8,
    review_count: 96,
    featured: 0,
    is_new: 1,
    image_url: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&q=80',
    description: 'Double-walled vacuum insulated 18/8 food grade stainless steel flask keeping water ice cold for 24 hours with chug spout and paracord carry loop.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&q=80']),
    specifications: JSON.stringify({ 'Capacity': '1500ml (50 oz)', 'Insulation': '24h Cold / 12h Hot', 'Steel': 'Pro-Grade 18/8 Stainless' })
  },
  {
    id: 78,
    name: 'FlexTone Adjustable Ankle & Wrist Weights Set',
    slug: 'flextone-adjustable-ankle-wrist-weights-set',
    category_id: 4,
    price: 1499,
    discount_percent: 15,
    stock: 36,
    rating: 4.7,
    review_count: 55,
    featured: 0,
    is_new: 1,
    image_url: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&q=80',
    description: 'Pair of wearable weighted bracelets with removable steel weight bars wrapped in waterproof sweatproof silicone for jogging, pilates, and aerobics.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&q=80']),
    specifications: JSON.stringify({ 'Total Weight': '1kg each (2kg pair)', 'Segments': '8 Removable Stainless Steel Bars', 'Material': 'Recycled Soft Silicone' })
  },
  {
    id: 79,
    name: 'GymGrip Wrist Wraps & Lifting Straps Set',
    slug: 'gymgrip-wrist-wraps-lifting-straps-set',
    category_id: 4,
    price: 699,
    discount_percent: 20,
    stock: 70,
    rating: 4.8,
    review_count: 88,
    featured: 0,
    is_new: 0,
    image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&q=80',
    description: 'Heavy duty thumb-loop elastic wrist wraps paired with silicone-padded cotton deadlift lasso straps for maximum wrist stability.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&q=80']),
    specifications: JSON.stringify({ 'Set Includes': '1 Pair 18" Wrist Wraps + 1 Pair Padded Lifting Straps' })
  },

  // Accessories Expansion (category_id: 5)
  {
    id: 80,
    name: 'StormGuard Windproof Teflon Travel Umbrella',
    slug: 'stormguard-windproof-teflon-travel-umbrella',
    category_id: 5,
    price: 1499,
    discount_percent: 15,
    stock: 45,
    rating: 4.8,
    review_count: 62,
    featured: 0,
    is_new: 1,
    image_url: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800&q=80',
    description: 'Compact 10-rib reinforced fiberglass frame umbrella with 210T Teflon water-repellent canopy, auto open/close button, and ergonomic rubber handle.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800&q=80']),
    specifications: JSON.stringify({ 'Ribs': '10-Rib Reinforced Resin-Fiberglass', 'Canopy': '210T High-Density Teflon Coated', 'Operation': 'One-Touch Auto Open & Close' })
  },
  {
    id: 81,
    name: 'Nomad Waterproof Hiking Daypack',
    slug: 'nomad-waterproof-hiking-daypack',
    category_id: 5,
    price: 3199,
    discount_percent: 22,
    stock: 25,
    rating: 4.7,
    review_count: 49,
    featured: 0,
    is_new: 0,
    image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80',
    description: 'Ultralight 30L outdoor trail daypack with integrated rainfly cover, trekking pole loops, and hydration bladder port.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80']),
    specifications: JSON.stringify({ 'Weight': '680 grams', 'Rain Cover': 'Included High-Vis Orange Rainfly' })
  },
  {
    id: 82,
    name: 'Saffiano Leather Structured Tote Bag',
    slug: 'saffiano-leather-structured-tote-bag',
    category_id: 5,
    price: 4599,
    discount_percent: 15,
    stock: 24,
    rating: 4.9,
    review_count: 73,
    featured: 1,
    is_new: 1,
    image_url: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&q=80',
    description: 'Scratch-resistant cross-grain Saffiano leather tote with dedicated padded tablet compartment, zip closure, and gold metal feet.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&q=80']),
    specifications: JSON.stringify({ 'Material': 'Genuine Saffiano Leather', 'Drop': '24cm Shoulder Handles' })
  },
  {
    id: 83,
    name: 'Minimalist Crossbody Saddle Bag',
    slug: 'minimalist-crossbody-saddle-bag',
    category_id: 5,
    price: 2699,
    discount_percent: 20,
    stock: 35,
    rating: 4.7,
    review_count: 56,
    featured: 0,
    is_new: 1,
    image_url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=80',
    description: 'Curved equestrian-inspired leather saddle bag with magnetic snap flap, interior card pocket, and adjustable crossbody strap.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=80']),
    specifications: JSON.stringify({ 'Leather': 'Smooth Full Grain Cowhide', 'Hardware': 'Brushed Brass' })
  },
  {
    id: 84,
    name: 'TechPouch Water-Resistant Cable & Gear Organizer',
    slug: 'techpouch-water-resistant-cable-gear-organizer',
    category_id: 5,
    price: 1899,
    discount_percent: 15,
    stock: 45,
    rating: 4.8,
    review_count: 67,
    featured: 0,
    is_new: 1,
    image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80',
    description: 'Origami-style unfolding electronic accessories organizer with elastic cable loops, SD card slots, power bank pocket, and weatherproof recycled nylon shell.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80']),
    specifications: JSON.stringify({ 'Shell': 'Weatherproof 200D Recycled Nylon', 'Pockets': '18 Internal Elastic Loops & Compartments', 'Dimensions': '24 x 15 x 10 cm' })
  },
  {
    id: 85,
    name: 'Zippered Travel Currency & Card Clutch',
    slug: 'zippered-travel-currency-card-clutch',
    category_id: 5,
    price: 1899,
    discount_percent: 25,
    stock: 30,
    rating: 4.6,
    review_count: 44,
    featured: 0,
    is_new: 0,
    image_url: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&q=80',
    description: 'Zip-around leather continental wallet with 12 card slots, zippered coin pouch, smartphone sleeve, and detachable wristlet loop.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&q=80']),
    specifications: JSON.stringify({ 'Zippers': 'YKK Metal Smooth Glide', 'Slots': '12 Cards + Passport Pocket' })
  },
  {
    id: 86,
    name: 'Aviator Polarized Titanium Sunglasses',
    slug: 'aviator-polarized-titanium-sunglasses',
    category_id: 5,
    price: 3299,
    discount_percent: 20,
    stock: 32,
    rating: 4.8,
    review_count: 85,
    featured: 1,
    is_new: 1,
    image_url: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&q=80',
    description: 'Ultralight Japanese titanium frame aviator sunglasses fitted with 9-layer TAC polarized lenses and 100% UV400 blocking.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&q=80']),
    specifications: JSON.stringify({ 'Frame': 'Beta-Titanium 18g', 'Lenses': 'Polarized TAC UV400 Category 3' })
  },
  {
    id: 87,
    name: 'Pure Mongolian Cashmere Fringed Winter Scarf',
    slug: 'pure-mongolian-cashmere-fringed-winter-scarf',
    category_id: 5,
    price: 3499,
    discount_percent: 15,
    stock: 30,
    rating: 4.9,
    review_count: 52,
    featured: 0,
    is_new: 1,
    image_url: 'https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=800&q=80',
    description: 'Cloud-soft woven wrap scarf spun from 100% authentic Grade-A Mongolian cashmere with delicate fringed edges and timeless heather grey weave.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=800&q=80']),
    specifications: JSON.stringify({ 'Material': '100% Grade-A Mongolian Cashmere', 'Dimensions': '180cm x 35cm + 8cm Fringe', 'Care': 'Dry Clean or Gentle Hand Wash' })
  },
  {
    id: 88,
    name: 'Full-Grain Italian Leather Reversible Belt',
    slug: 'full-grain-italian-leather-reversible-belt',
    category_id: 5,
    price: 1999,
    discount_percent: 10,
    stock: 40,
    rating: 4.7,
    review_count: 53,
    featured: 0,
    is_new: 0,
    image_url: 'https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=800&q=80',
    description: 'Two-in-one reversible leather dress belt flipping smoothly between Black and Cognac Brown with a brushed zinc swivel buckle.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=800&q=80']),
    specifications: JSON.stringify({ 'Leather': 'Tuscan Full-Grain Vegetable Tanned', 'Width': '34mm Formal Standard' })
  },
  {
    id: 89,
    name: 'ChronoClassic Automatic Mechanical Watch',
    slug: 'chronoclassic-automatic-mechanical-watch',
    category_id: 5,
    price: 14999,
    discount_percent: 15,
    stock: 14,
    rating: 4.9,
    review_count: 46,
    featured: 1,
    is_new: 1,
    image_url: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&q=80',
    description: 'Self-winding mechanical automatic timepiece with 41-hour power reserve, exhibition sapphire caseback, and genuine alligator grain strap.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&q=80']),
    specifications: JSON.stringify({ 'Movement': 'Japanese Miyota 9015 Automatic (28,800 vph)', 'Water Resistance': '50m' })
  },
  {
    id: 90,
    name: 'Voyager Waxed Canvas & Leather Weekender Duffle',
    slug: 'voyager-waxed-canvas-leather-weekender-duffle',
    category_id: 5,
    price: 4999,
    discount_percent: 18,
    stock: 22,
    rating: 4.9,
    review_count: 62,
    featured: 1,
    is_new: 1,
    image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80',
    description: '45L rugged water-resistant 18oz waxed canvas overnight duffel bag with heavy-duty top-grain leather straps, shoe tunnel, and brass hardware.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80']),
    specifications: JSON.stringify({ 'Capacity': '45 Litres (Carry-On Approved)', 'Fabric': '18 oz Heavy-Duty Beeswax Canvas', 'Trim': 'Full-Grain Crazy Horse Cowhide' })
  },
  {
    id: 91,
    name: 'Hardshell Carry-On Spinner Suitcase',
    slug: 'hardshell-carry-on-spinner-suitcase',
    category_id: 5,
    price: 5999,
    discount_percent: 20,
    stock: 20,
    rating: 4.9,
    review_count: 75,
    featured: 1,
    is_new: 0,
    image_url: 'https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?w=800&q=80',
    description: 'Aviation-grade 100% polycarbonate 20-inch carry-on with whisper-silent 360-degree Hinomoto dual wheels and integrated TSA lock.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?w=800&q=80']),
    specifications: JSON.stringify({ 'Capacity': '38 Litres', 'Shell': 'Covestro Makrolon Polycarbonate', 'Lock': 'TSA Approved 007' })
  },

  // Gadgets Expansion (category_id: 6)
  {
    id: 92,
    name: 'Apex Wireless Low-Profile Keyboard',
    slug: 'apex-wireless-low-profile-keyboard',
    category_id: 6,
    price: 4999,
    discount_percent: 15,
    stock: 30,
    rating: 4.8,
    review_count: 72,
    featured: 1,
    is_new: 1,
    image_url: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=800&q=80',
    description: 'Slimline wireless mechanical keyboard with ultra-thin Gateron low-profile switches, aluminum top plate, and Mac/Windows switch.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=800&q=80']),
    specifications: JSON.stringify({ 'Profile': 'Ultra-thin Low Profile (18mm)', 'Switches': 'Low Profile Mechanical Red' })
  },
  {
    id: 93,
    name: 'Precision 64-in-1 Electric Screwdriver Toolkit',
    slug: 'precision-64-in-1-electric-screwdriver-toolkit',
    category_id: 6,
    price: 2699,
    discount_percent: 20,
    stock: 35,
    rating: 4.9,
    review_count: 78,
    featured: 0,
    is_new: 1,
    image_url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&q=80',
    description: 'Cordless rechargeable electric precision screwdriver with 64 magnetic S2 steel bits, shadowless circular LED worklight, and pop-up magnetic storage case.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&q=80']),
    specifications: JSON.stringify({ 'Bits': '64 S2 Tool Steel Precision Bits (HRC 60)', 'Torque': 'Electric 0.25-0.35 N.m / Manual 3 N.m', 'Speed': '200 RPM Dual Direction' })
  },
  {
    id: 94,
    name: 'Precision Master MX Ergonomic Vertical Mouse',
    slug: 'precision-master-mx-ergonomic-vertical-mouse',
    category_id: 6,
    price: 3699,
    discount_percent: 12,
    stock: 35,
    rating: 4.9,
    review_count: 88,
    featured: 1,
    is_new: 0,
    image_url: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&q=80',
    description: '57-degree natural handshake angle wireless vertical mouse reducing wrist pressure, with magnetic thumb scroll wheel and multi-OS flow.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&q=80']),
    specifications: JSON.stringify({ 'Angle': '57° Natural Ergonomic', 'Sensor': '4000 DPI Darkfield Laser (Works on Glass)' })
  },
  {
    id: 95,
    name: 'Dual Wireless Lavalier Microphone System',
    slug: 'dual-wireless-lavalier-microphone-system',
    category_id: 6,
    price: 3899,
    discount_percent: 22,
    stock: 38,
    rating: 4.8,
    review_count: 92,
    featured: 0,
    is_new: 1,
    image_url: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=800&q=80',
    description: 'Plug-and-play 2.4GHz wireless lapel mic set for iPhone, Android, and cameras with active DSP noise cancellation, 65ft range, and 24h charging case.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=800&q=80']),
    specifications: JSON.stringify({ 'Transmission': '2.4GHz Low Latency (15ms)', 'Range': '20 meters / 65 feet clear line of sight', 'Set': '2 Transmitters + 1 Receiver + Case' })
  },
  {
    id: 96,
    name: 'StreamClear 4K HDR Streaming Webcam',
    slug: 'streamclear-4k-hdr-streaming-webcam',
    category_id: 6,
    price: 6499,
    discount_percent: 20,
    stock: 24,
    rating: 4.8,
    review_count: 67,
    featured: 1,
    is_new: 1,
    image_url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&q=80',
    description: 'Ultra HD 4K 60FPS webcam with Sony STARVIS sensor, AI auto-framing, dual noise-cancelling microphones, and physical privacy shutter.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&q=80']),
    specifications: JSON.stringify({ 'Resolution': '4K @ 30FPS / 1080p @ 60FPS HDR', 'Field of View': 'Adjustable 65° / 78° / 90°' })
  },
  {
    id: 97,
    name: '360° Rotating Aluminum Ergonomic Laptop Stand',
    slug: '360-rotating-aluminum-ergonomic-laptop-stand',
    category_id: 6,
    price: 2199,
    discount_percent: 18,
    stock: 42,
    rating: 4.8,
    review_count: 64,
    featured: 0,
    is_new: 0,
    image_url: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&q=80',
    description: 'Heavy-duty CNC anodized aluminum riser with 360-degree swivel base, dual-axis height and angle adjustability, and heat dissipation cooling vents.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&q=80']),
    specifications: JSON.stringify({ 'Material': 'Solid Anodized Aluminum Alloy', 'Swivel': '360 Degree Smooth Click Rotation', 'Compatibility': 'All Laptops 10" to 17.3"' })
  },
  {
    id: 98,
    name: 'PowerVault 25000mAh 140W Laptop Power Bank',
    slug: 'powervault-25000mah-140w-laptop-power-bank',
    category_id: 6,
    price: 6999,
    discount_percent: 15,
    stock: 26,
    rating: 4.9,
    review_count: 81,
    featured: 1,
    is_new: 1,
    image_url: 'https://images.unsplash.com/photo-1609592807904-4e2b02447eb5?w=800&q=80',
    description: 'High-capacity airline approved power bank with Power Delivery 3.1 140W output capable of fast charging a 16-inch MacBook Pro and phone simultaneously.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1609592807904-4e2b02447eb5?w=800&q=80']),
    specifications: JSON.stringify({ 'Capacity': '25,000mAh (90Wh Airline Safe)', 'Max Output': '140W USB-C PD 3.1' })
  },
  {
    id: 99,
    name: 'PocketJuice 10000mAh Magnetic Power Bank',
    slug: 'pocketjuice-10000mah-magnetic-power-bank',
    category_id: 6,
    price: 2499,
    discount_percent: 20,
    stock: 50,
    rating: 4.7,
    review_count: 94,
    featured: 0,
    is_new: 1,
    image_url: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&q=80',
    description: 'Ultra-compact MagSafe compatible magnetic snap-on wireless power bank with foldable ring kickstand and 20W wired USB-C fast charging.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&q=80']),
    specifications: JSON.stringify({ 'Capacity': '10,000mAh', 'Wireless': '15W MagSafe Snap', 'Wired Output': '20W PD' })
  },
  {
    id: 100,
    name: 'GaNFast 100W 4-Port USB-C Desktop Charger',
    slug: 'ganfast-100w-4-port-usb-c-desktop-charger',
    category_id: 6,
    price: 3899,
    discount_percent: 18,
    stock: 36,
    rating: 4.8,
    review_count: 73,
    featured: 1,
    is_new: 0,
    image_url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&q=80',
    description: 'Gallium Nitride (GaN III) compact 4-port fast wall charger with intelligent power distribution across 3 USB-C and 1 USB-A ports.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&q=80']),
    specifications: JSON.stringify({ 'Technology': 'Navitas GaN III Semiconductor', 'Total Power': '100W Max', 'Ports': '3x USB-C + 1x USB-A' })
  },
  {
    id: 101,
    name: 'Pocket Thermal Mini Label & Sticker Printer',
    slug: 'pocket-thermal-mini-label-sticker-printer',
    category_id: 6,
    price: 1899,
    discount_percent: 20,
    stock: 46,
    rating: 4.7,
    review_count: 63,
    featured: 0,
    is_new: 1,
    image_url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&q=80',
    description: 'Inkless Bluetooth thermal label maker connecting directly to iOS and Android apps for printing storage labels, price tags, barcodes, and craft notes.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&q=80']),
    specifications: JSON.stringify({ 'Print Tech': 'Direct Thermal (Zero Ink/Toner)', 'Resolution': '203 DPI Crisp Print', 'Label Width': '12mm - 15mm' })
  },
  {
    id: 102,
    name: 'Smart Air Quality & Desk Monitor',
    slug: 'smart-air-quality-desk-monitor',
    category_id: 6,
    price: 3499,
    discount_percent: 22,
    stock: 28,
    rating: 4.7,
    review_count: 39,
    featured: 0,
    is_new: 1,
    image_url: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&q=80',
    description: 'Real-time laser particulate monitor measuring CO2, PM2.5, VOCs, temperature, and humidity with clear e-ink crisp display and WiFi syncing.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&q=80']),
    specifications: JSON.stringify({ 'Sensors': 'NDIR CO2 + Laser Scattering PM2.5', 'Display': 'Paper-like E-Ink Screen' })
  },
  {
    id: 103,
    name: 'NovaDock 12-in-1 Thunderbolt 4 Dock',
    slug: 'novadock-12-in-1-thunderbolt-4-dock',
    category_id: 6,
    price: 12999,
    discount_percent: 15,
    stock: 15,
    rating: 4.9,
    review_count: 48,
    featured: 1,
    is_new: 1,
    image_url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&q=80',
    description: 'Aluminum hub delivering dual 4K 60Hz or single 8K monitor output, 90W host charging, Gigabit Ethernet, SD 4.0, and 40Gbps Thunderbolt speeds.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&q=80']),
    specifications: JSON.stringify({ 'Bandwidth': '40Gbps Thunderbolt 4', 'Host Power': '90W Laptop Passthrough', 'Displays': 'Dual 4K @ 60Hz' })
  },
  {
    id: 104,
    name: 'LumiGlow RGB Ambient Desk Lightbar',
    slug: 'lumiglow-rgb-ambient-desk-lightbar',
    category_id: 6,
    price: 2799,
    discount_percent: 25,
    stock: 35,
    rating: 4.8,
    review_count: 92,
    featured: 0,
    is_new: 1,
    image_url: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&q=80',
    description: 'Asymmetric screen monitor lightbar that eliminates screen glare while casting vibrant rear RGB reactive ambient backlight onto the wall.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&q=80']),
    specifications: JSON.stringify({ 'Lighting': 'Front Ra95 Asymmetric + Rear RGB Sync', 'Control': 'Wireless Desktop Rotary Dial' })
  },
  {
    id: 105,
    name: 'TouchPad Ergonomic Trackpad Pro',
    slug: 'touchpad-ergonomic-trackpad-pro',
    category_id: 6,
    price: 3999,
    discount_percent: 10,
    stock: 22,
    rating: 4.7,
    review_count: 43,
    featured: 0,
    is_new: 0,
    image_url: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&q=80',
    description: 'Precision multi-touch frosted glass trackpad with haptic feedback vibration, smooth gesture support for Windows and Mac, and Bluetooth 5.2.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&q=80']),
    specifications: JSON.stringify({ 'Surface': 'Frosted Ultra-Smooth Tempered Glass', 'Gestures': '1 to 4 Finger Gesture Navigation' })
  },

  // Completing Electronics (category_id: 1) to 20 products
  {
    id: 106,
    name: 'BeamCast 4K Streaming Dongle',
    slug: 'beamcast-4k-streaming-dongle',
    category_id: 1,
    price: 3499,
    discount_percent: 20,
    stock: 45,
    rating: 4.7,
    review_count: 79,
    featured: 0,
    is_new: 1,
    image_url: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&q=80',
    description: 'Ultra-compact 4K HDR media streamer with Dolby Vision Atmos support, WiFi 6, and voice assistant remote control.',
    additional_images: JSON.stringify(['https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&q=80']),
    specifications: JSON.stringify({ 'Resolution': '4K UHD 60FPS Dolby Vision', 'Audio': 'Dolby Atmos Passthrough', 'Network': 'Dual-Band WiFi 6' })
  }
];
